const data = [
  {
    id: 1,
    imageUrl: "./ImgMembers/aku.jpg",
    name: "Okechukwu Ahamefule",
    title: "Akuo Ulo 1.",
    occupation: "Buisness Man",
    city: "Berlin",
    country: "Germany",
    contact: "Ask for",
  },
  {
    id: 2,
    imageUrl: "./ImgMembers/charlespicF.jpg",
    name: "Jane Smith",
    title: "",
    occupation: "Buisness Man",
    city: "Berlin",
    country: "Germany",
    contact: "Ask for",
  },
  {
    id: 3,
    imageUrl: "./ImgMembers/pro-pic.png",
    name: "Jane Smith",
    title: "",
    occupation: "Buisness Man",
    city: "Berlin",
    country: "Germany",
    contact: "Ask for",
  },
  {
    id: 4,
    imageUrl: "./ImgMembers/IkonsoPic.jpg",
    name: "Jane Smith",
    title: "",
    occupation: "Buisness Man",
    city: "Berlin",
    country: "Germany",
    contact: "Ask for",
  },
  {
    id: 5,
    imageUrl: "./ImgMembers/young.jpg",
    name: "Jane Smith",
    title: "",
    occupation: "Buisness Man",
    city: "Berlin",
    country: "Germany",
    contact: "Ask for",
  },
  {
    id: 6,
    imageUrl: "./ImgMembers/Nwaka.jpg",
    name: "Jane Smith",
    title: "",
    occupation: "Buisness Man",
    city: "Berlin",
    country: "Germany",
    contact: "Ask for",
  },
  {
    id: 7,
    imageUrl: "./ImgMembers/ken.jpg",
    name: "Jane Smith",
    title: "",
    occupation: "Buisness Man",
    city: "Berlin",
    country: "Germany",
    contact: "Ask for",
  },
  {
    id: 8,
    imageUrl: "./ImgMembers/Ogazi.jpg",
    name: "Jane Smith",
    title: "",
    occupation: "Buisness Man",
    city: "Berlin",
    country: "Germany",
    contact: "Ask for",
  },

  // Add more data objects as needed
];

export default data;
