const data = [
  {
    id: 1,
    imageUrl: "./ImgMembers/aku.jpg",
    name: "Okechukwu Ahamefule",
    title: "Chief Akuo Ulo 1.",
    position:"Chairman Doings",
    occupation: "Buisness Man",
    city: "Berlin",
    country: "Germany",
    contact: "Ask for",
  },
  {
    id: 2,
    imageUrl: "./ImgMembers/charlespicF.jpg",
    name: "Charles Ohaeri",
    title: "Chief Okanimee 1.",
    position:"Vice Chairman",
    occupation: "Buisness Man",
    city: "Berlin",
    country: "Germany",
    contact: "Ask for",
  },
  {
    id: 3,
    imageUrl: "./ImgMembers/pro-pic.png",
    name: "Kingsley Nwachukwu",
    title: "A.K.A Rawmetal",
    position:"Secretary",
    occupation: "Web & App Developer",
    city: "Berlin",
    country: "Germany",
    contact: "Ask for",
  },
  {
    id: 4,
    imageUrl: "./ImgMembers/IkonsoPic.jpg",
    name: "Morris Ogbonna",
    title: "A.k.A Iko Triple B",
    position:"",
    occupation: "Buisness Man",
    city: "Berlin",
    country: "Germany",
    contact: "Ask for",
  },
  {
    id: 5,
    imageUrl: "./ImgMembers/young.jpg",
    name: "Ifeany Onyeoziri",
    title: "A.K.A Young Money",
    position:"Active Member",
    occupation: "Importer & Exporter",
    city: "Berlin",
    country: "Germany",
    contact: "Ask for",
  },
  {
    id: 6,
    imageUrl: "./ImgMembers/Nwaka.jpg",
    name: "Kingsley Ikeh",
    title: "A.K.A Nwakaibeya 1",
    position:"Active Member",
    occupation: "Buisness Man",
    city: "Berlin",
    country: "Germany",
    contact: "Ask for",
  },
  {
    id: 7,
    imageUrl: "./ImgMembers/ken.jpg",
    name: "Kenneth Ekoh",
    title: "A.K.A Owemi",
    position:"Active Member",
    occupation: "Buisness Man",
    city: "Berlin",
    country: "Germany",
    contact: "Ask for",
  },
  {
    id: 8,
    imageUrl: "./ImgMembers/Ogazi.jpg",
    name: "Ugochukwu Molokwu",
    title: "A.K.A Ogazi Amaka",
    position:"Active Member",
    occupation: "Buisness Man",
    city: "Berlin",
    country: "Germany",
    contact: "Ask for",
  },

  // Add more data objects as needed
];

export default data;
